server:
  port: 8080

spring:
  application:
    name: UserService
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce_userservicedb
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect


jwt:
  secret: sgRZt0pZT3qmuzqC5EQcFLVrxyoWSoZKmvRR8vmQ8Ps=
  expiration: 600000



